baseURL = "http://doc/doc"
title = "SysDC"
theme = "hugo-theme-learn"
languageCode = "ja-JP"
defaultContentLanguage = "ja"
canonifyurls = true

[outputs]
home = ["HTML", "JSON"]

[params]
titleSeparator = "|"
themeVariant = "blue"
disableLandingPageButton = true
disableShortcutsTitle = true

[Languages]
[Languages.ja]
weight = 1
languageName = "日本語"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> SysDC"
identifier = "github-sysdc"
url = "https://github.com/Yuta1004/SysDC"
weight = 1

[[Languages.ja.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> SysDC-Web (this site)"
identifier = "github-sysdc-web"
url = "https://github.com/Yuta1004/SysDC-Web"
weight = 2

[[Languages.ja.menu.shortcuts]]
name = "<i class='fa-sharp fa-solid fa-laptop-code'></i> SecHack365"
identifier = "sechack365"
url = "https://sechack365.nict.go.jp/"
weight = 3
