name: check

on:
  push:
    branches:
      - "master"
      - "develop*"
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: Build
      run: cargo build --all-targets
      working-directory: core

  fmt:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: Setup rustup
      run: rustup component add rustfmt
    - name: Check format
      run: cargo fmt --all -- --check
      working-directory: core

  clippy:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: Setup rustup
      run: rustup component add clippy
    - name: Check by Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: core

  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: Test
      run: cargo test --all
      working-directory: core
